language: node_js
node_js:
  - "node"
notifications:
  email: false
before_script:
  - sudo setcap cap_net_bind_service=+ep `which node`
  - cd ../database && /bin/bash ../shell/populate-db.sh
  - npm run start &
script: npm test
sudo: required
services: mongodb
