language: node_js
node_js:
  - "node"
notifications:
  email: false
before_install: cd application
before_script:
  - /bin/bash ../shell/setup-vm.sh
  - cd ../database && /bin/bash ../shell/populate-db.sh
script: cd ../application && npm test
sudo: required
services: mongodb