db.taxons.drop();
db.taxons.insert([
	{ "taxon": "Abies alba", "vernacularName": "Sapin blanc", "periods": ["E"], "potential": 25, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Abies_alba" },
	{ "taxon": "Acer campestre", "vernacularName": "Érable champêtre", "periods": ["V2"], "potential": 800, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89rable_champ%C3%AAtre" },
	{ "taxon": "Acer platanoïdes", "vernacularName": "Érable plane", "periods": ["V1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89rable_plane" },
	{ "taxon": "Acer pseudoplatanus", "vernacularName": "Érable sycomore", "periods": ["V2"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89rable_sycomore" },
	{ "taxon": "Aesculus", "vernacularName": "Aesculus", "periods": ["V2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Aesculus" },
	{ "taxon": "Ajuga repens", "vernacularName": "Bugle rampante", "periods": ["V1","V2","V3","V4"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bugle_rampante" },
	{ "taxon": "Alliaria officinalis", "vernacularName": "Alliaire officinale", "periods": ["V1","V2","V3","V4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Alliaire_officinale" },
	{ "taxon": "Allium ursinum", "vernacularName": "Ail des ours", "periods": ["V1","V2","V3","V4"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Allium_ursinum" },
	{ "taxon": "Anemone nemorosa", "vernacularName": "Anémone sylvie", "periods": ["PV1","PV2"], "potential": 0, "wikipediaUrl":"https://fr.wikipedia.org/wiki/An%C3%A9mone_sylvie" },
	{ "taxon": "Angelica", "vernacularName": "Angélique", "periods": ["E1","E2","T4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Angelica" },
	{ "taxon": "Anthriscus sylvestris", "vernacularName": "Cerfeuil sauvage", "periods": ["V2"], "potential": 25, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cerfeuil_sauvage" },
	{ "taxon": "Arctium", "vernacularName": "Bardanes", "periods": ["E2"], "potential": 400, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bardane" },
	{ "taxon": "Asperula odorata", "vernacularName": "Aspérule odorante", "periods": ["V1","V2","V3","V4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Galium_odoratum" },
	{ "taxon": "Crepis", "vernacularName": "Crépides", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Crepis" },
	{ "taxon": "Leontodon", "vernacularName": "Liondents", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Leontodon" },
	{ "taxon": "Sonchus", "vernacularName": "Laiterons", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Sonchus" },
	{ "taxon": "Bellis perennis", "vernacularName": "Pâquerette", "periods": ["V1","V2","V3","V4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/P%C3%A2querette" },
	{ "taxon": "Berberis vulgaris", "vernacularName": "Épine-vinette", "periods": ["V1","V2","V3","V4"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89pine-vinette" },
	{ "taxon": "Betula", "vernacularName": "Bouleau", "periods": ["V1","V2","V3","V4"], "potential": 0, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bouleau" },
	{ "taxon": "Borago officinalis", "vernacularName": "Bourrache officinale", "periods": ["E1","E2"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bourrache_officinale" },
	{ "taxon": "Brassica napus", "vernacularName": "Colza", "periods": ["V1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Colza" },
	{ "taxon": "Brassica nigra", "vernacularName": "Moutarde noire", "periods": ["E1","E2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Moutarde_noire" },
	{ "taxon": "Calluna vulgaris", "vernacularName": "Callune", "periods": ["EA"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Calluna_vulgaris" },
	{ "taxon": "Campanula", "vernacularName": "Campanule", "periods": ["E1","E2"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Campanule" },
	{ "taxon": "Cardamine pratensis", "vernacularName": "Cardamine des prés", "periods": ["V1","V2","V3","V4","T2"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cardamine_des_pr%C3%A9s" },
	{ "taxon": "Carduus", "vernacularName": "Vrais chardons", "periods": ["E1","E2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Carduus" },
	{ "taxon": "Castanea sativa", "vernacularName": "Châtaignier", "periods": ["E1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Castanea_sativa" },
	{ "taxon": "Centaurea", "vernacularName": "Centaurées", "periods": ["E1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Centaurea" },
	{ "taxon": "Cichorium intybus", "vernacularName": "Chicorée sauvage", "periods": ["E1","E2","EA"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cichorium_intybus" },
	{ "taxon": "Cirsium", "vernacularName": "Cirse", "periods": ["E1","E2"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cirse" },
	{ "taxon": "Convolvulus", "vernacularName": "Convolvulus", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Convolvulus" },
	{ "taxon": "Cornus mas", "vernacularName": "Cornouiller mâle", "periods": ["PV1","PV2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cornus_mas" }
]);
