/*global db*/
db.taxons.drop();
db.taxons.insert([ // TAXREF v10.0
	{ "_id":1, "name": "Abies alba", "vernacularName": "Sapin", "periods": ["E"], "potential": 25, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Abies_alba" },
	{ "_id":2, "name": "Acer campestre", "vernacularName": "Érable champêtre", "periods": ["V2"], "potential": 800, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89rable_champ%C3%AAtre" },
	{ "_id":3, "name": "Acer platanoïdes", "vernacularName": "Érable plane", "periods": ["V1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89rable_plane" },
	{ "_id":4, "name": "Acer pseudoplatanus", "vernacularName": "Érable sycomore", "periods": ["V2"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89rable_sycomore" },
	{ "_id":5, "name": "Aesculus", "vernacularName": "Aesculus", "periods": ["V2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Aesculus" },
	{ "_id":6, "name": "Ajuga repens", "vernacularName": "Bugle rampante", "periods": ["V1","V2","V3","V4"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bugle_rampante" },
	{ "_id":7, "name": "Alliaria officinalis", "vernacularName": "Alliaire officinale", "periods": ["V1","V2","V3","V4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Alliaire_officinale" },
	{ "_id":8, "name": "Allium ursinum", "vernacularName": "Ail des ours", "periods": ["V1","V2","V3","V4"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Allium_ursinum" },
	{ "_id":9, "name": "Anemone nemorosa", "vernacularName": "Anémone sylvie", "periods": ["PV1","PV2"], "potential": 0, "wikipediaUrl":"https://fr.wikipedia.org/wiki/An%C3%A9mone_sylvie" },
	{ "_id":10, "name": "Angelica", "vernacularName": "Angélique", "periods": ["E1","E2","T4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Angelica" },
	{ "_id":11, "name": "Anthriscus sylvestris", "vernacularName": "Cerfeuil sauvage", "periods": ["V2"], "potential": 25, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cerfeuil_sauvage" },
	{ "_id":12, "name": "Arctium", "vernacularName": "Bardanes", "periods": ["E2"], "potential": 400, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bardane" },
	{ "_id":13, "name": "Asperula odorata", "vernacularName": "Aspérule odorante", "periods": ["V1","V2","V3","V4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Galium_odoratum" },
	{ "_id":14, "name": "Crepis", "vernacularName": "Crépides", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Crepis" },
	{ "_id":15, "name": "Leontodon", "vernacularName": "Liondents", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Leontodon" },
	{ "_id":16, "name": "Sonchus", "vernacularName": "Laiterons", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Sonchus" },
	{ "_id":17, "name": "Bellis perennis", "vernacularName": "Pâquerette", "periods": ["V1","V2","V3","V4"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/P%C3%A2querette" },
	{ "_id":18, "name": "Berberis vulgaris", "vernacularName": "Épine-vinette", "periods": ["V1","V2","V3","V4"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/%C3%89pine-vinette" },
	{ "_id":19, "name": "Betula", "vernacularName": "Bouleau", "periods": ["V1","V2","V3","V4"], "potential": 0, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bouleau" },
	{ "_id":20, "name": "Borago officinalis", "vernacularName": "Bourrache officinale", "periods": ["E1","E2"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Bourrache_officinale" },
	{ "_id":21, "name": "Brassica napus", "vernacularName": "Colza", "periods": ["V1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Colza" },
	{ "_id":22, "name": "Brassica nigra", "vernacularName": "Moutarde noire", "periods": ["E1","E2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Moutarde_noire" },
	{ "_id":23, "name": "Calluna vulgaris", "vernacularName": "Callune", "periods": ["EA"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Calluna_vulgaris" },
	{ "_id":24, "name": "Campanula", "vernacularName": "Campanule", "periods": ["E1","E2"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Campanule" },
	{ "_id":25, "name": "Cardamine pratensis", "vernacularName": "Cardamine des prés", "periods": ["V1","V2","V3","V4","T2"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cardamine_des_pr%C3%A9s" },
	{ "_id":26, "name": "Carduus", "vernacularName": "Vrais chardons", "periods": ["E1","E2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Carduus" },
	{ "_id":27, "name": "Castanea sativa", "vernacularName": "Châtaignier", "periods": ["E1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Castanea_sativa" },
	{ "_id":28, "name": "Centaurea", "vernacularName": "Centaurées", "periods": ["E1"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Centaurea" },
	{ "_id":29, "name": "Cichorium intybus", "vernacularName": "Chicorée sauvage", "periods": ["E1","E2","EA"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cichorium_intybus" },
	{ "_id":30, "name": "Cirsium", "vernacularName": "Cirse", "periods": ["E1","E2"], "potential": 200, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cirse" },
	{ "_id":31, "name": "Convolvulus", "vernacularName": "Convolvulus", "periods": ["E1","E2","EA"], "potential": 50, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Convolvulus" },
	{ "_id":32, "name": "Cornus mas", "vernacularName": "Cornouiller mâle", "periods": ["PV1","PV2"], "potential": 100, "wikipediaUrl":"https://fr.wikipedia.org/wiki/Cornus_mas" }
]);
